version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    hostname: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ngcash
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  api:
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend


volumes:
  postgres-data:

networks:
    backend:
      external: true